services:
  # 1. The Python Background Daemon
  - type: web
    name: drone-telemetry-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python daemon.py
    envVars:
      - key: EXECUTION_MODE
        value: TEST

  # 2. The Frontend User Interface Dashboard
  - type: web
    name: drone-telemetry-ui
    runtime: static
    plan: free
    staticPublishPath: ./
